// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace RyanPenfold.SolutionMaker.UI.Windows
{
    using System.Windows.Forms;

    partial class MappingsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MappingsForm));
            this.MainPanel = new System.Windows.Forms.Panel();
            this.MappingsDataGridView = new System.Windows.Forms.DataGridView();
            this.CancelButton = new System.Windows.Forms.Button();
            this.OKButton = new System.Windows.Forms.Button();
            this.DuplicatesMessageLabel = new System.Windows.Forms.Label();
            this.EmptyCellMessageLabel = new System.Windows.Forms.Label();
            this.MainPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.MappingsDataGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // MainPanel
            // 
            this.MainPanel.AutoScroll = true;
            this.MainPanel.Controls.Add(this.MappingsDataGridView);
            this.MainPanel.Location = new System.Drawing.Point(0, 0);
            this.MainPanel.Name = "MainPanel";
            this.MainPanel.Size = new System.Drawing.Size(1274, 639);
            this.MainPanel.TabIndex = 0;
            // 
            // MappingsDataGridView
            // 
            this.MappingsDataGridView.AllowUserToAddRows = false;
            this.MappingsDataGridView.AllowUserToDeleteRows = false;
            this.MappingsDataGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.MappingsDataGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MappingsDataGridView.Location = new System.Drawing.Point(0, 0);
            this.MappingsDataGridView.Name = "MappingsDataGridView";
            this.MappingsDataGridView.ReadOnly = true;
            this.MappingsDataGridView.RowTemplate.Height = 28;
            this.MappingsDataGridView.Size = new System.Drawing.Size(1274, 639);
            this.MappingsDataGridView.TabIndex = 0;
            this.MappingsDataGridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.MappingsDataGridView_CellClick);
            this.MappingsDataGridView.CellValueChanged += new System.Windows.Forms.DataGridViewCellEventHandler(this.MappingsDataGridView_CellValueChanged);
            this.MappingsDataGridView.DataBindingComplete += new System.Windows.Forms.DataGridViewBindingCompleteEventHandler(this.MappingsDataGridView_DataBindingComplete);
            // 
            // CancelButton
            // 
            this.CancelButton.Location = new System.Drawing.Point(640, 645);
            this.CancelButton.Name = "CancelButton";
            this.CancelButton.Size = new System.Drawing.Size(75, 37);
            this.CancelButton.TabIndex = 3;
            this.CancelButton.Text = "Cancel";
            this.CancelButton.UseVisualStyleBackColor = true;
            this.CancelButton.Click += new System.EventHandler(this.CancelButton_Click);
            // 
            // OKButton
            // 
            this.OKButton.Location = new System.Drawing.Point(559, 645);
            this.OKButton.Name = "OKButton";
            this.OKButton.Size = new System.Drawing.Size(75, 37);
            this.OKButton.TabIndex = 2;
            this.OKButton.Text = "OK";
            this.OKButton.UseVisualStyleBackColor = true;
            this.OKButton.Click += new System.EventHandler(this.OKButton_Click);
            // 
            // DuplicatesMessageLabel
            // 
            this.DuplicatesMessageLabel.AutoSize = true;
            this.DuplicatesMessageLabel.ForeColor = System.Drawing.Color.Red;
            this.DuplicatesMessageLabel.Location = new System.Drawing.Point(242, 653);
            this.DuplicatesMessageLabel.Name = "DuplicatesMessageLabel";
            this.DuplicatesMessageLabel.Size = new System.Drawing.Size(297, 20);
            this.DuplicatesMessageLabel.TabIndex = 4;
            this.DuplicatesMessageLabel.Text = "Please correct any duplicate type names.";
            this.DuplicatesMessageLabel.Visible = false;
            // 
            // EmptyCellMessageLabel
            // 
            this.EmptyCellMessageLabel.AutoSize = true;
            this.EmptyCellMessageLabel.ForeColor = System.Drawing.Color.Red;
            this.EmptyCellMessageLabel.Location = new System.Drawing.Point(734, 653);
            this.EmptyCellMessageLabel.Name = "EmptyCellMessageLabel";
            this.EmptyCellMessageLabel.Size = new System.Drawing.Size(276, 20);
            this.EmptyCellMessageLabel.TabIndex = 5;
            this.EmptyCellMessageLabel.Text = "Please correct any empty type names.";
            this.EmptyCellMessageLabel.Visible = false;
            // 
            // MappingsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1275, 694);
            this.Controls.Add(this.EmptyCellMessageLabel);
            this.Controls.Add(this.DuplicatesMessageLabel);
            this.Controls.Add(this.CancelButton);
            this.Controls.Add(this.OKButton);
            this.Controls.Add(this.MainPanel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(1297, 750);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(1297, 750);
            this.Name = "MappingsForm";
            this.Text = "Solution Maker - Confirm Mappings";
            this.Load += new System.EventHandler(this.MappingsForm_Load);
            this.MainPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.MappingsDataGridView)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel MainPanel;
        private new System.Windows.Forms.Button CancelButton;
        private System.Windows.Forms.Button OKButton;
        private System.Windows.Forms.DataGridView MappingsDataGridView;
        private Label DuplicatesMessageLabel;
        private Label EmptyCellMessageLabel;
    }
}