// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace RyanPenfold.SolutionMaker.UI.Windows
{
    /// <summary>
    /// The main form
    /// </summary>
    public partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.OpenFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.UpdateProjectFilesCheckBox = new System.Windows.Forms.CheckBox();
            this.VisualBasicRadioButton = new System.Windows.Forms.RadioButton();
            this.CSharpRadioButton = new System.Windows.Forms.RadioButton();
            this.RootNamespaceLabel = new System.Windows.Forms.Label();
            this.RootNamespaceTextBox = new System.Windows.Forms.TextBox();
            this.CompanyNameLabel = new System.Windows.Forms.Label();
            this.CompanyNameTextBox = new System.Windows.Forms.TextBox();
            this.ModelProjectNamespaceLabel = new System.Windows.Forms.Label();
            this.ModelProjectNamespaceTextBox = new System.Windows.Forms.TextBox();
            this.OutputDirectoryLabel = new System.Windows.Forms.Label();
            this.OutputDirectoryTextBox = new System.Windows.Forms.TextBox();
            this.OpenOutputDirectoryButton = new System.Windows.Forms.Button();
            this.BrowseOutputDirectoryButton = new System.Windows.Forms.Button();
            this.LogLabel = new System.Windows.Forms.Label();
            this.LogTextBox = new System.Windows.Forms.TextBox();
            this.GoButton = new System.Windows.Forms.Button();
            this.SelectDeselectAllPOCOTypesLinkLabel = new System.Windows.Forms.LinkLabel();
            this.POCOTypesCheckedListBox = new System.Windows.Forms.CheckedListBox();
            this.POCOTypesLabel = new System.Windows.Forms.Label();
            this.AssemblyLocationLabel = new System.Windows.Forms.Label();
            this.AssemblyLocationTextBox = new System.Windows.Forms.TextBox();
            this.BrowseAssemblyLocationButton = new System.Windows.Forms.Button();
            this.OpenAssemblyLocationButton = new System.Windows.Forms.Button();
            this.RefreshPOCOListLinkLabel = new System.Windows.Forms.LinkLabel();
            this.SelectDeselectAllDBObjectsLinkLabel = new System.Windows.Forms.LinkLabel();
            this.StoredProceduresCheckBox = new System.Windows.Forms.CheckBox();
            this.ViewsCheckBox = new System.Windows.Forms.CheckBox();
            this.TablesCheckBox = new System.Windows.Forms.CheckBox();
            this.DBObjectsCheckedListBox = new System.Windows.Forms.CheckedListBox();
            this.RefreshDBListLinkLabel = new System.Windows.Forms.LinkLabel();
            this.DatabaseObjectsLabel = new System.Windows.Forms.Label();
            this.ConnectionStringTextBox = new System.Windows.Forms.TextBox();
            this.ConnectionStringLabel = new System.Windows.Forms.Label();
            this.OutputFolderBrowserDialog = new System.Windows.Forms.FolderBrowserDialog();
            this.RepositoryProjectNamespaceLabel = new System.Windows.Forms.Label();
            this.RepositoryProjectNamespaceTextBox = new System.Windows.Forms.TextBox();
            this.ServiceProjectNamespaceLabel = new System.Windows.Forms.Label();
            this.ServiceProjectNamespaceTextBox = new System.Windows.Forms.TextBox();
            this.DeleteContentsLinkLabel = new System.Windows.Forms.LinkLabel();
            this.ClearLogLinkLabel = new System.Windows.Forms.LinkLabel();
            this.TableValuedFunctionsCheckBox = new System.Windows.Forms.CheckBox();
            this.ClearDBObjectsLinkLabel = new System.Windows.Forms.LinkLabel();
            this.ClearPOCOTypesLinkLabel = new System.Windows.Forms.LinkLabel();
            this.ProgressBar = new System.Windows.Forms.ProgressBar();
            this.ProgressLabel = new System.Windows.Forms.Label();
            this.ResetLinkLabel = new System.Windows.Forms.LinkLabel();
            this.BuiltInTypeTextBox = new System.Windows.Forms.TextBox();
            this.AddBuiltInTypeButton = new System.Windows.Forms.Button();
            this.AddBuiltInTypeLabel = new System.Windows.Forms.Label();
            this.CopyToClipboardLinkLabel = new System.Windows.Forms.LinkLabel();
            this.SaveLogAsLinkLabel = new System.Windows.Forms.LinkLabel();
            this.SaveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.OpenIocMappingsConfigFileButton = new System.Windows.Forms.Button();
            this.BrowseIocMappingsConfigFileButton = new System.Windows.Forms.Button();
            this.IocMappingsConfigFilePathTextBox = new System.Windows.Forms.TextBox();
            this.IocMappingsConfigFileLabel = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // OpenFileDialog
            // 
            this.OpenFileDialog.Title = "Open File";
            // 
            // UpdateProjectFilesCheckBox
            // 
            this.UpdateProjectFilesCheckBox.AutoSize = true;
            this.UpdateProjectFilesCheckBox.Location = new System.Drawing.Point(455, 302);
            this.UpdateProjectFilesCheckBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.UpdateProjectFilesCheckBox.Name = "UpdateProjectFilesCheckBox";
            this.UpdateProjectFilesCheckBox.Size = new System.Drawing.Size(172, 24);
            this.UpdateProjectFilesCheckBox.TabIndex = 11;
            this.UpdateProjectFilesCheckBox.Text = "Update project files";
            this.UpdateProjectFilesCheckBox.UseVisualStyleBackColor = true;
            this.UpdateProjectFilesCheckBox.CheckedChanged += new System.EventHandler(this.SaveSettings);
            // 
            // VisualBasicRadioButton
            // 
            this.VisualBasicRadioButton.AutoSize = true;
            this.VisualBasicRadioButton.Location = new System.Drawing.Point(77, 301);
            this.VisualBasicRadioButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.VisualBasicRadioButton.Name = "VisualBasicRadioButton";
            this.VisualBasicRadioButton.Size = new System.Drawing.Size(56, 24);
            this.VisualBasicRadioButton.TabIndex = 10;
            this.VisualBasicRadioButton.Text = "VB";
            this.VisualBasicRadioButton.UseVisualStyleBackColor = true;
            this.VisualBasicRadioButton.CheckedChanged += new System.EventHandler(this.SaveSettings);
            // 
            // CSharpRadioButton
            // 
            this.CSharpRadioButton.AutoSize = true;
            this.CSharpRadioButton.Checked = true;
            this.CSharpRadioButton.Location = new System.Drawing.Point(15, 301);
            this.CSharpRadioButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.CSharpRadioButton.Name = "CSharpRadioButton";
            this.CSharpRadioButton.Size = new System.Drawing.Size(54, 24);
            this.CSharpRadioButton.TabIndex = 9;
            this.CSharpRadioButton.TabStop = true;
            this.CSharpRadioButton.Text = "C#";
            this.CSharpRadioButton.UseVisualStyleBackColor = true;
            this.CSharpRadioButton.CheckedChanged += new System.EventHandler(this.SaveSettings);
            // 
            // RootNamespaceLabel
            // 
            this.RootNamespaceLabel.AutoSize = true;
            this.RootNamespaceLabel.Location = new System.Drawing.Point(11, 388);
            this.RootNamespaceLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.RootNamespaceLabel.Name = "RootNamespaceLabel";
            this.RootNamespaceLabel.Size = new System.Drawing.Size(613, 20);
            this.RootNamespaceLabel.TabIndex = 14;
            this.RootNamespaceLabel.Text = "Root namespace (where BusinessBase.Infrastructure and NHibernateRepository are)";
            // 
            // RootNamespaceTextBox
            // 
            this.RootNamespaceTextBox.Location = new System.Drawing.Point(14, 413);
            this.RootNamespaceTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.RootNamespaceTextBox.Name = "RootNamespaceTextBox";
            this.RootNamespaceTextBox.Size = new System.Drawing.Size(613, 26);
            this.RootNamespaceTextBox.TabIndex = 15;
            this.RootNamespaceTextBox.TextChanged += new System.EventHandler(this.SaveSettings);
            // 
            // CompanyNameLabel
            // 
            this.CompanyNameLabel.AutoSize = true;
            this.CompanyNameLabel.Location = new System.Drawing.Point(10, 330);
            this.CompanyNameLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.CompanyNameLabel.Name = "CompanyNameLabel";
            this.CompanyNameLabel.Size = new System.Drawing.Size(120, 20);
            this.CompanyNameLabel.TabIndex = 12;
            this.CompanyNameLabel.Text = "Company name";
            // 
            // CompanyNameTextBox
            // 
            this.CompanyNameTextBox.Location = new System.Drawing.Point(14, 355);
            this.CompanyNameTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.CompanyNameTextBox.Name = "CompanyNameTextBox";
            this.CompanyNameTextBox.Size = new System.Drawing.Size(613, 26);
            this.CompanyNameTextBox.TabIndex = 13;
            this.CompanyNameTextBox.TextChanged += new System.EventHandler(this.SaveSettings);
            // 
            // ModelProjectNamespaceLabel
            // 
            this.ModelProjectNamespaceLabel.AutoSize = true;
            this.ModelProjectNamespaceLabel.Location = new System.Drawing.Point(12, 446);
            this.ModelProjectNamespaceLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ModelProjectNamespaceLabel.Name = "ModelProjectNamespaceLabel";
            this.ModelProjectNamespaceLabel.Size = new System.Drawing.Size(191, 20);
            this.ModelProjectNamespaceLabel.TabIndex = 16;
            this.ModelProjectNamespaceLabel.Text = "Model project namespace";
            // 
            // ModelProjectNamespaceTextBox
            // 
            this.ModelProjectNamespaceTextBox.Location = new System.Drawing.Point(14, 471);
            this.ModelProjectNamespaceTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ModelProjectNamespaceTextBox.Name = "ModelProjectNamespaceTextBox";
            this.ModelProjectNamespaceTextBox.Size = new System.Drawing.Size(613, 26);
            this.ModelProjectNamespaceTextBox.TabIndex = 17;
            this.ModelProjectNamespaceTextBox.TextChanged += new System.EventHandler(this.SaveSettings);
            // 
            // OutputDirectoryLabel
            // 
            this.OutputDirectoryLabel.AutoSize = true;
            this.OutputDirectoryLabel.Location = new System.Drawing.Point(643, 330);
            this.OutputDirectoryLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.OutputDirectoryLabel.Name = "OutputDirectoryLabel";
            this.OutputDirectoryLabel.Size = new System.Drawing.Size(122, 20);
            this.OutputDirectoryLabel.TabIndex = 30;
            this.OutputDirectoryLabel.Text = "Output directory";
            // 
            // OutputDirectoryTextBox
            // 
            this.OutputDirectoryTextBox.Location = new System.Drawing.Point(645, 355);
            this.OutputDirectoryTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.OutputDirectoryTextBox.Name = "OutputDirectoryTextBox";
            this.OutputDirectoryTextBox.Size = new System.Drawing.Size(450, 26);
            this.OutputDirectoryTextBox.TabIndex = 31;
            this.OutputDirectoryTextBox.TextChanged += new System.EventHandler(this.OutputDirectoryTextBox_TextChanged);
            // 
            // OpenOutputDirectoryButton
            // 
            this.OpenOutputDirectoryButton.Location = new System.Drawing.Point(1185, 351);
            this.OpenOutputDirectoryButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.OpenOutputDirectoryButton.Name = "OpenOutputDirectoryButton";
            this.OpenOutputDirectoryButton.Size = new System.Drawing.Size(75, 35);
            this.OpenOutputDirectoryButton.TabIndex = 33;
            this.OpenOutputDirectoryButton.Text = "Open";
            this.OpenOutputDirectoryButton.UseVisualStyleBackColor = true;
            this.OpenOutputDirectoryButton.Click += new System.EventHandler(this.OpenOutputDirectoryButton_Click);
            // 
            // BrowseOutputDirectoryButton
            // 
            this.BrowseOutputDirectoryButton.Location = new System.Drawing.Point(1102, 351);
            this.BrowseOutputDirectoryButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.BrowseOutputDirectoryButton.Name = "BrowseOutputDirectoryButton";
            this.BrowseOutputDirectoryButton.Size = new System.Drawing.Size(75, 35);
            this.BrowseOutputDirectoryButton.TabIndex = 32;
            this.BrowseOutputDirectoryButton.Text = "Browse";
            this.BrowseOutputDirectoryButton.UseVisualStyleBackColor = true;
            this.BrowseOutputDirectoryButton.Click += new System.EventHandler(this.BrowseOutputDirectoryButton_Click);
            // 
            // LogLabel
            // 
            this.LogLabel.AutoSize = true;
            this.LogLabel.Location = new System.Drawing.Point(641, 505);
            this.LogLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.LogLabel.Name = "LogLabel";
            this.LogLabel.Size = new System.Drawing.Size(36, 20);
            this.LogLabel.TabIndex = 36;
            this.LogLabel.Text = "Log";
            // 
            // LogTextBox
            // 
            this.LogTextBox.BackColor = System.Drawing.Color.White;
            this.LogTextBox.ForeColor = System.Drawing.SystemColors.ControlText;
            this.LogTextBox.Location = new System.Drawing.Point(645, 529);
            this.LogTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.LogTextBox.Multiline = true;
            this.LogTextBox.Name = "LogTextBox";
            this.LogTextBox.ReadOnly = true;
            this.LogTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.LogTextBox.Size = new System.Drawing.Size(616, 86);
            this.LogTextBox.TabIndex = 37;
            // 
            // GoButton
            // 
            this.GoButton.Location = new System.Drawing.Point(9, 630);
            this.GoButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.GoButton.Name = "GoButton";
            this.GoButton.Size = new System.Drawing.Size(1253, 55);
            this.GoButton.TabIndex = 38;
            this.GoButton.Text = "Go";
            this.GoButton.UseVisualStyleBackColor = true;
            this.GoButton.Click += new System.EventHandler(this.GoButton_Click);
            // 
            // SelectDeselectAllPOCOTypesLinkLabel
            // 
            this.SelectDeselectAllPOCOTypesLinkLabel.AutoSize = true;
            this.SelectDeselectAllPOCOTypesLinkLabel.Location = new System.Drawing.Point(850, 70);
            this.SelectDeselectAllPOCOTypesLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.SelectDeselectAllPOCOTypesLinkLabel.Name = "SelectDeselectAllPOCOTypesLinkLabel";
            this.SelectDeselectAllPOCOTypesLinkLabel.Size = new System.Drawing.Size(145, 20);
            this.SelectDeselectAllPOCOTypesLinkLabel.TabIndex = 28;
            this.SelectDeselectAllPOCOTypesLinkLabel.TabStop = true;
            this.SelectDeselectAllPOCOTypesLinkLabel.Text = "Select / deselect all";
            this.SelectDeselectAllPOCOTypesLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.SelectDeselectAllPOCOTypesLinkLabel_LinkClicked);
            // 
            // POCOTypesCheckedListBox
            // 
            this.POCOTypesCheckedListBox.FormattingEnabled = true;
            this.POCOTypesCheckedListBox.Location = new System.Drawing.Point(645, 94);
            this.POCOTypesCheckedListBox.Name = "POCOTypesCheckedListBox";
            this.POCOTypesCheckedListBox.Size = new System.Drawing.Size(616, 172);
            this.POCOTypesCheckedListBox.TabIndex = 27;
            this.POCOTypesCheckedListBox.SelectedIndexChanged += new System.EventHandler(this.POCOTypesCheckedListBox_SelectedIndexChanged);
            // 
            // POCOTypesLabel
            // 
            this.POCOTypesLabel.AutoSize = true;
            this.POCOTypesLabel.Location = new System.Drawing.Point(641, 70);
            this.POCOTypesLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.POCOTypesLabel.Name = "POCOTypesLabel";
            this.POCOTypesLabel.Size = new System.Drawing.Size(96, 20);
            this.POCOTypesLabel.TabIndex = 55;
            this.POCOTypesLabel.Text = "POCO types";
            // 
            // AssemblyLocationLabel
            // 
            this.AssemblyLocationLabel.AutoSize = true;
            this.AssemblyLocationLabel.Location = new System.Drawing.Point(641, 9);
            this.AssemblyLocationLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.AssemblyLocationLabel.Name = "AssemblyLocationLabel";
            this.AssemblyLocationLabel.Size = new System.Drawing.Size(136, 20);
            this.AssemblyLocationLabel.TabIndex = 22;
            this.AssemblyLocationLabel.Text = "Assembly location";
            // 
            // AssemblyLocationTextBox
            // 
            this.AssemblyLocationTextBox.Location = new System.Drawing.Point(645, 35);
            this.AssemblyLocationTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.AssemblyLocationTextBox.Name = "AssemblyLocationTextBox";
            this.AssemblyLocationTextBox.ReadOnly = true;
            this.AssemblyLocationTextBox.Size = new System.Drawing.Size(450, 26);
            this.AssemblyLocationTextBox.TabIndex = 23;
            this.AssemblyLocationTextBox.TextChanged += new System.EventHandler(this.SaveSettings);
            // 
            // BrowseAssemblyLocationButton
            // 
            this.BrowseAssemblyLocationButton.Location = new System.Drawing.Point(1103, 32);
            this.BrowseAssemblyLocationButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.BrowseAssemblyLocationButton.Name = "BrowseAssemblyLocationButton";
            this.BrowseAssemblyLocationButton.Size = new System.Drawing.Size(75, 35);
            this.BrowseAssemblyLocationButton.TabIndex = 24;
            this.BrowseAssemblyLocationButton.Text = "Browse";
            this.BrowseAssemblyLocationButton.UseVisualStyleBackColor = true;
            this.BrowseAssemblyLocationButton.Click += new System.EventHandler(this.BrowseAssemblyLocationButton_Click);
            // 
            // OpenAssemblyLocationButton
            // 
            this.OpenAssemblyLocationButton.Location = new System.Drawing.Point(1186, 32);
            this.OpenAssemblyLocationButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.OpenAssemblyLocationButton.Name = "OpenAssemblyLocationButton";
            this.OpenAssemblyLocationButton.Size = new System.Drawing.Size(75, 35);
            this.OpenAssemblyLocationButton.TabIndex = 25;
            this.OpenAssemblyLocationButton.Text = "Open";
            this.OpenAssemblyLocationButton.UseVisualStyleBackColor = true;
            this.OpenAssemblyLocationButton.Click += new System.EventHandler(this.OpenAssemblyLocationButton_Click);
            // 
            // RefreshPOCOListLinkLabel
            // 
            this.RefreshPOCOListLinkLabel.AutoSize = true;
            this.RefreshPOCOListLinkLabel.Location = new System.Drawing.Point(748, 70);
            this.RefreshPOCOListLinkLabel.Name = "RefreshPOCOListLinkLabel";
            this.RefreshPOCOListLinkLabel.Size = new System.Drawing.Size(89, 20);
            this.RefreshPOCOListLinkLabel.TabIndex = 26;
            this.RefreshPOCOListLinkLabel.TabStop = true;
            this.RefreshPOCOListLinkLabel.Text = "Refresh list";
            this.RefreshPOCOListLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.RefreshPOCOListLinkLabel_LinkClicked);
            // 
            // SelectDeselectAllDBObjectsLinkLabel
            // 
            this.SelectDeselectAllDBObjectsLinkLabel.AutoSize = true;
            this.SelectDeselectAllDBObjectsLinkLabel.Location = new System.Drawing.Point(256, 71);
            this.SelectDeselectAllDBObjectsLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.SelectDeselectAllDBObjectsLinkLabel.Name = "SelectDeselectAllDBObjectsLinkLabel";
            this.SelectDeselectAllDBObjectsLinkLabel.Size = new System.Drawing.Size(145, 20);
            this.SelectDeselectAllDBObjectsLinkLabel.TabIndex = 8;
            this.SelectDeselectAllDBObjectsLinkLabel.TabStop = true;
            this.SelectDeselectAllDBObjectsLinkLabel.Text = "Select / deselect all";
            this.SelectDeselectAllDBObjectsLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.SelectDeselectAllDBObjectsLinkLabel_LinkClicked);
            // 
            // StoredProceduresCheckBox
            // 
            this.StoredProceduresCheckBox.AutoSize = true;
            this.StoredProceduresCheckBox.Location = new System.Drawing.Point(187, 270);
            this.StoredProceduresCheckBox.Name = "StoredProceduresCheckBox";
            this.StoredProceduresCheckBox.Size = new System.Drawing.Size(167, 24);
            this.StoredProceduresCheckBox.TabIndex = 7;
            this.StoredProceduresCheckBox.Text = "Stored procedures";
            this.StoredProceduresCheckBox.UseVisualStyleBackColor = true;
            this.StoredProceduresCheckBox.CheckedChanged += new System.EventHandler(this.SaveSettings);
            // 
            // ViewsCheckBox
            // 
            this.ViewsCheckBox.AutoSize = true;
            this.ViewsCheckBox.Location = new System.Drawing.Point(104, 270);
            this.ViewsCheckBox.Name = "ViewsCheckBox";
            this.ViewsCheckBox.Size = new System.Drawing.Size(77, 24);
            this.ViewsCheckBox.TabIndex = 6;
            this.ViewsCheckBox.Text = "Views";
            this.ViewsCheckBox.UseVisualStyleBackColor = true;
            this.ViewsCheckBox.CheckedChanged += new System.EventHandler(this.SaveSettings);
            // 
            // TablesCheckBox
            // 
            this.TablesCheckBox.AutoSize = true;
            this.TablesCheckBox.Checked = true;
            this.TablesCheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this.TablesCheckBox.Location = new System.Drawing.Point(16, 270);
            this.TablesCheckBox.Name = "TablesCheckBox";
            this.TablesCheckBox.Size = new System.Drawing.Size(82, 24);
            this.TablesCheckBox.TabIndex = 5;
            this.TablesCheckBox.Text = "Tables";
            this.TablesCheckBox.UseVisualStyleBackColor = true;
            this.TablesCheckBox.CheckedChanged += new System.EventHandler(this.SaveSettings);
            // 
            // DBObjectsCheckedListBox
            // 
            this.DBObjectsCheckedListBox.FormattingEnabled = true;
            this.DBObjectsCheckedListBox.Location = new System.Drawing.Point(16, 93);
            this.DBObjectsCheckedListBox.Name = "DBObjectsCheckedListBox";
            this.DBObjectsCheckedListBox.Size = new System.Drawing.Size(610, 172);
            this.DBObjectsCheckedListBox.TabIndex = 4;
            // 
            // RefreshDBListLinkLabel
            // 
            this.RefreshDBListLinkLabel.AutoSize = true;
            this.RefreshDBListLinkLabel.Location = new System.Drawing.Point(154, 71);
            this.RefreshDBListLinkLabel.Name = "RefreshDBListLinkLabel";
            this.RefreshDBListLinkLabel.Size = new System.Drawing.Size(89, 20);
            this.RefreshDBListLinkLabel.TabIndex = 3;
            this.RefreshDBListLinkLabel.TabStop = true;
            this.RefreshDBListLinkLabel.Text = "Refresh list";
            this.RefreshDBListLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.RefreshDBListLinkLabel_LinkClicked);
            // 
            // DatabaseObjectsLabel
            // 
            this.DatabaseObjectsLabel.AutoSize = true;
            this.DatabaseObjectsLabel.Location = new System.Drawing.Point(11, 70);
            this.DatabaseObjectsLabel.Name = "DatabaseObjectsLabel";
            this.DatabaseObjectsLabel.Size = new System.Drawing.Size(134, 20);
            this.DatabaseObjectsLabel.TabIndex = 2;
            this.DatabaseObjectsLabel.Text = "Database objects";
            // 
            // ConnectionStringTextBox
            // 
            this.ConnectionStringTextBox.Location = new System.Drawing.Point(16, 35);
            this.ConnectionStringTextBox.Name = "ConnectionStringTextBox";
            this.ConnectionStringTextBox.Size = new System.Drawing.Size(610, 26);
            this.ConnectionStringTextBox.TabIndex = 1;
            this.ConnectionStringTextBox.TextChanged += new System.EventHandler(this.SaveSettings);
            // 
            // ConnectionStringLabel
            // 
            this.ConnectionStringLabel.AutoSize = true;
            this.ConnectionStringLabel.Location = new System.Drawing.Point(12, 9);
            this.ConnectionStringLabel.Name = "ConnectionStringLabel";
            this.ConnectionStringLabel.Size = new System.Drawing.Size(133, 20);
            this.ConnectionStringLabel.TabIndex = 0;
            this.ConnectionStringLabel.Text = "Connection string";
            // 
            // RepositoryProjectNamespaceLabel
            // 
            this.RepositoryProjectNamespaceLabel.AutoSize = true;
            this.RepositoryProjectNamespaceLabel.Location = new System.Drawing.Point(12, 504);
            this.RepositoryProjectNamespaceLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.RepositoryProjectNamespaceLabel.Name = "RepositoryProjectNamespaceLabel";
            this.RepositoryProjectNamespaceLabel.Size = new System.Drawing.Size(224, 20);
            this.RepositoryProjectNamespaceLabel.TabIndex = 18;
            this.RepositoryProjectNamespaceLabel.Text = "Repository project namespace";
            // 
            // RepositoryProjectNamespaceTextBox
            // 
            this.RepositoryProjectNamespaceTextBox.Location = new System.Drawing.Point(13, 529);
            this.RepositoryProjectNamespaceTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.RepositoryProjectNamespaceTextBox.Name = "RepositoryProjectNamespaceTextBox";
            this.RepositoryProjectNamespaceTextBox.Size = new System.Drawing.Size(613, 26);
            this.RepositoryProjectNamespaceTextBox.TabIndex = 19;
            this.RepositoryProjectNamespaceTextBox.TextChanged += new System.EventHandler(this.SaveSettings);
            // 
            // ServiceProjectNamespaceLabel
            // 
            this.ServiceProjectNamespaceLabel.AutoSize = true;
            this.ServiceProjectNamespaceLabel.Location = new System.Drawing.Point(12, 562);
            this.ServiceProjectNamespaceLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ServiceProjectNamespaceLabel.Name = "ServiceProjectNamespaceLabel";
            this.ServiceProjectNamespaceLabel.Size = new System.Drawing.Size(200, 20);
            this.ServiceProjectNamespaceLabel.TabIndex = 20;
            this.ServiceProjectNamespaceLabel.Text = "Service project namespace";
            // 
            // ServiceProjectNamespaceTextBox
            // 
            this.ServiceProjectNamespaceTextBox.Location = new System.Drawing.Point(13, 587);
            this.ServiceProjectNamespaceTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ServiceProjectNamespaceTextBox.Name = "ServiceProjectNamespaceTextBox";
            this.ServiceProjectNamespaceTextBox.Size = new System.Drawing.Size(613, 26);
            this.ServiceProjectNamespaceTextBox.TabIndex = 21;
            this.ServiceProjectNamespaceTextBox.TextChanged += new System.EventHandler(this.SaveSettings);
            // 
            // DeleteContentsLinkLabel
            // 
            this.DeleteContentsLinkLabel.AutoSize = true;
            this.DeleteContentsLinkLabel.Location = new System.Drawing.Point(776, 330);
            this.DeleteContentsLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.DeleteContentsLinkLabel.Name = "DeleteContentsLinkLabel";
            this.DeleteContentsLinkLabel.Size = new System.Drawing.Size(204, 20);
            this.DeleteContentsLinkLabel.TabIndex = 57;
            this.DeleteContentsLinkLabel.TabStop = true;
            this.DeleteContentsLinkLabel.Text = "Delete contents of directory";
            this.DeleteContentsLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.DeleteContentsLinkLabel_LinkClicked);
            // 
            // ClearLogLinkLabel
            // 
            this.ClearLogLinkLabel.AutoSize = true;
            this.ClearLogLinkLabel.Location = new System.Drawing.Point(685, 505);
            this.ClearLogLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ClearLogLinkLabel.Name = "ClearLogLinkLabel";
            this.ClearLogLinkLabel.Size = new System.Drawing.Size(46, 20);
            this.ClearLogLinkLabel.TabIndex = 58;
            this.ClearLogLinkLabel.TabStop = true;
            this.ClearLogLinkLabel.Text = "Clear";
            this.ClearLogLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ClearLogLinkLabel_LinkClicked);
            // 
            // TableValuedFunctionsCheckBox
            // 
            this.TableValuedFunctionsCheckBox.AutoSize = true;
            this.TableValuedFunctionsCheckBox.Location = new System.Drawing.Point(361, 270);
            this.TableValuedFunctionsCheckBox.Name = "TableValuedFunctionsCheckBox";
            this.TableValuedFunctionsCheckBox.Size = new System.Drawing.Size(193, 24);
            this.TableValuedFunctionsCheckBox.TabIndex = 59;
            this.TableValuedFunctionsCheckBox.Text = "Table valued functions";
            this.TableValuedFunctionsCheckBox.UseVisualStyleBackColor = true;
            this.TableValuedFunctionsCheckBox.CheckedChanged += new System.EventHandler(this.SaveSettings);
            // 
            // ClearDBObjectsLinkLabel
            // 
            this.ClearDBObjectsLinkLabel.AutoSize = true;
            this.ClearDBObjectsLinkLabel.Location = new System.Drawing.Point(414, 71);
            this.ClearDBObjectsLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ClearDBObjectsLinkLabel.Name = "ClearDBObjectsLinkLabel";
            this.ClearDBObjectsLinkLabel.Size = new System.Drawing.Size(46, 20);
            this.ClearDBObjectsLinkLabel.TabIndex = 60;
            this.ClearDBObjectsLinkLabel.TabStop = true;
            this.ClearDBObjectsLinkLabel.Text = "Clear";
            this.ClearDBObjectsLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ClearDBObjectsLinkLabel_LinkClicked);
            // 
            // ClearPOCOTypesLinkLabel
            // 
            this.ClearPOCOTypesLinkLabel.AutoSize = true;
            this.ClearPOCOTypesLinkLabel.Location = new System.Drawing.Point(1008, 70);
            this.ClearPOCOTypesLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ClearPOCOTypesLinkLabel.Name = "ClearPOCOTypesLinkLabel";
            this.ClearPOCOTypesLinkLabel.Size = new System.Drawing.Size(46, 20);
            this.ClearPOCOTypesLinkLabel.TabIndex = 61;
            this.ClearPOCOTypesLinkLabel.TabStop = true;
            this.ClearPOCOTypesLinkLabel.Text = "Clear";
            this.ClearPOCOTypesLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ClearPOCOTypesLinkLabel_LinkClicked);
            // 
            // ProgressBar
            // 
            this.ProgressBar.Location = new System.Drawing.Point(647, 471);
            this.ProgressBar.Name = "ProgressBar";
            this.ProgressBar.Size = new System.Drawing.Size(613, 31);
            this.ProgressBar.TabIndex = 62;
            // 
            // ProgressLabel
            // 
            this.ProgressLabel.AutoSize = true;
            this.ProgressLabel.Location = new System.Drawing.Point(641, 447);
            this.ProgressLabel.Name = "ProgressLabel";
            this.ProgressLabel.Size = new System.Drawing.Size(72, 20);
            this.ProgressLabel.TabIndex = 63;
            this.ProgressLabel.Text = "Progress";
            // 
            // ResetLinkLabel
            // 
            this.ResetLinkLabel.AutoSize = true;
            this.ResetLinkLabel.Location = new System.Drawing.Point(722, 448);
            this.ResetLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.ResetLinkLabel.Name = "ResetLinkLabel";
            this.ResetLinkLabel.Size = new System.Drawing.Size(52, 20);
            this.ResetLinkLabel.TabIndex = 64;
            this.ResetLinkLabel.TabStop = true;
            this.ResetLinkLabel.Text = "Reset";
            this.ResetLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ResetLinkLabel_LinkClicked);
            // 
            // BuiltInTypeTextBox
            // 
            this.BuiltInTypeTextBox.Location = new System.Drawing.Point(645, 299);
            this.BuiltInTypeTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.BuiltInTypeTextBox.Name = "BuiltInTypeTextBox";
            this.BuiltInTypeTextBox.Size = new System.Drawing.Size(532, 26);
            this.BuiltInTypeTextBox.TabIndex = 65;
            this.BuiltInTypeTextBox.TextChanged += new System.EventHandler(this.BuiltInTypeTextBox_TextChanged);
            // 
            // AddBuiltInTypeButton
            // 
            this.AddBuiltInTypeButton.Location = new System.Drawing.Point(1185, 295);
            this.AddBuiltInTypeButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.AddBuiltInTypeButton.Name = "AddBuiltInTypeButton";
            this.AddBuiltInTypeButton.Size = new System.Drawing.Size(75, 35);
            this.AddBuiltInTypeButton.TabIndex = 66;
            this.AddBuiltInTypeButton.Text = "Add";
            this.AddBuiltInTypeButton.UseVisualStyleBackColor = true;
            this.AddBuiltInTypeButton.Click += new System.EventHandler(this.AddBuiltInTypeButton_Click);
            // 
            // AddBuiltInTypeLabel
            // 
            this.AddBuiltInTypeLabel.AutoSize = true;
            this.AddBuiltInTypeLabel.Location = new System.Drawing.Point(646, 274);
            this.AddBuiltInTypeLabel.Name = "AddBuiltInTypeLabel";
            this.AddBuiltInTypeLabel.Size = new System.Drawing.Size(122, 20);
            this.AddBuiltInTypeLabel.TabIndex = 67;
            this.AddBuiltInTypeLabel.Text = "Add built-in type";
            // 
            // CopyToClipboardLinkLabel
            // 
            this.CopyToClipboardLinkLabel.AutoSize = true;
            this.CopyToClipboardLinkLabel.Location = new System.Drawing.Point(739, 505);
            this.CopyToClipboardLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.CopyToClipboardLinkLabel.Name = "CopyToClipboardLinkLabel";
            this.CopyToClipboardLinkLabel.Size = new System.Drawing.Size(131, 20);
            this.CopyToClipboardLinkLabel.TabIndex = 68;
            this.CopyToClipboardLinkLabel.TabStop = true;
            this.CopyToClipboardLinkLabel.Text = "Copy to clipboard";
            this.CopyToClipboardLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.CopyToClipboardLinkLabel_LinkClicked);
            // 
            // SaveLogAsLinkLabel
            // 
            this.SaveLogAsLinkLabel.AutoSize = true;
            this.SaveLogAsLinkLabel.Location = new System.Drawing.Point(878, 505);
            this.SaveLogAsLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.SaveLogAsLinkLabel.Name = "SaveLogAsLinkLabel";
            this.SaveLogAsLinkLabel.Size = new System.Drawing.Size(78, 20);
            this.SaveLogAsLinkLabel.TabIndex = 69;
            this.SaveLogAsLinkLabel.TabStop = true;
            this.SaveLogAsLinkLabel.Text = "Save as...";
            this.SaveLogAsLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.SaveLogAsLinkLabel_LinkClicked);
            // 
            // OpenIocMappingsConfigFileButton
            // 
            this.OpenIocMappingsConfigFileButton.Location = new System.Drawing.Point(1185, 409);
            this.OpenIocMappingsConfigFileButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.OpenIocMappingsConfigFileButton.Name = "OpenIocMappingsConfigFileButton";
            this.OpenIocMappingsConfigFileButton.Size = new System.Drawing.Size(75, 35);
            this.OpenIocMappingsConfigFileButton.TabIndex = 73;
            this.OpenIocMappingsConfigFileButton.Text = "Open";
            this.OpenIocMappingsConfigFileButton.UseVisualStyleBackColor = true;
            this.OpenIocMappingsConfigFileButton.Click += new System.EventHandler(this.OpenIocMappingsConfigFileButton_Click);
            // 
            // BrowseIocMappingsConfigFileButton
            // 
            this.BrowseIocMappingsConfigFileButton.Location = new System.Drawing.Point(1102, 409);
            this.BrowseIocMappingsConfigFileButton.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.BrowseIocMappingsConfigFileButton.Name = "BrowseIocMappingsConfigFileButton";
            this.BrowseIocMappingsConfigFileButton.Size = new System.Drawing.Size(75, 35);
            this.BrowseIocMappingsConfigFileButton.TabIndex = 72;
            this.BrowseIocMappingsConfigFileButton.Text = "Browse";
            this.BrowseIocMappingsConfigFileButton.UseVisualStyleBackColor = true;
            this.BrowseIocMappingsConfigFileButton.Click += new System.EventHandler(this.BrowseIocMappingsConfigFileButton_Click);
            // 
            // IocMappingsConfigFilePathTextBox
            // 
            this.IocMappingsConfigFilePathTextBox.Location = new System.Drawing.Point(645, 413);
            this.IocMappingsConfigFilePathTextBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.IocMappingsConfigFilePathTextBox.Name = "IocMappingsConfigFilePathTextBox";
            this.IocMappingsConfigFilePathTextBox.Size = new System.Drawing.Size(450, 26);
            this.IocMappingsConfigFilePathTextBox.TabIndex = 71;
            this.IocMappingsConfigFilePathTextBox.TextChanged += new System.EventHandler(this.IocMappingsConfigFileTextBox_TextChanged);
            // 
            // IocMappingsConfigFileLabel
            // 
            this.IocMappingsConfigFileLabel.AutoSize = true;
            this.IocMappingsConfigFileLabel.Location = new System.Drawing.Point(643, 388);
            this.IocMappingsConfigFileLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.IocMappingsConfigFileLabel.Name = "IocMappingsConfigFileLabel";
            this.IocMappingsConfigFileLabel.Size = new System.Drawing.Size(178, 20);
            this.IocMappingsConfigFileLabel.TabIndex = 70;
            this.IocMappingsConfigFileLabel.Text = "IoC mappings config file";
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1275, 694);
            this.Controls.Add(this.OpenIocMappingsConfigFileButton);
            this.Controls.Add(this.BrowseIocMappingsConfigFileButton);
            this.Controls.Add(this.IocMappingsConfigFilePathTextBox);
            this.Controls.Add(this.IocMappingsConfigFileLabel);
            this.Controls.Add(this.SaveLogAsLinkLabel);
            this.Controls.Add(this.CopyToClipboardLinkLabel);
            this.Controls.Add(this.AddBuiltInTypeLabel);
            this.Controls.Add(this.AddBuiltInTypeButton);
            this.Controls.Add(this.BuiltInTypeTextBox);
            this.Controls.Add(this.ResetLinkLabel);
            this.Controls.Add(this.ProgressLabel);
            this.Controls.Add(this.ProgressBar);
            this.Controls.Add(this.ClearPOCOTypesLinkLabel);
            this.Controls.Add(this.ClearDBObjectsLinkLabel);
            this.Controls.Add(this.TableValuedFunctionsCheckBox);
            this.Controls.Add(this.ClearLogLinkLabel);
            this.Controls.Add(this.DeleteContentsLinkLabel);
            this.Controls.Add(this.ServiceProjectNamespaceLabel);
            this.Controls.Add(this.ServiceProjectNamespaceTextBox);
            this.Controls.Add(this.RepositoryProjectNamespaceLabel);
            this.Controls.Add(this.RepositoryProjectNamespaceTextBox);
            this.Controls.Add(this.ConnectionStringLabel);
            this.Controls.Add(this.ConnectionStringTextBox);
            this.Controls.Add(this.DatabaseObjectsLabel);
            this.Controls.Add(this.RefreshDBListLinkLabel);
            this.Controls.Add(this.DBObjectsCheckedListBox);
            this.Controls.Add(this.TablesCheckBox);
            this.Controls.Add(this.ViewsCheckBox);
            this.Controls.Add(this.StoredProceduresCheckBox);
            this.Controls.Add(this.SelectDeselectAllDBObjectsLinkLabel);
            this.Controls.Add(this.RefreshPOCOListLinkLabel);
            this.Controls.Add(this.OpenAssemblyLocationButton);
            this.Controls.Add(this.BrowseAssemblyLocationButton);
            this.Controls.Add(this.AssemblyLocationTextBox);
            this.Controls.Add(this.AssemblyLocationLabel);
            this.Controls.Add(this.POCOTypesLabel);
            this.Controls.Add(this.POCOTypesCheckedListBox);
            this.Controls.Add(this.SelectDeselectAllPOCOTypesLinkLabel);
            this.Controls.Add(this.GoButton);
            this.Controls.Add(this.LogTextBox);
            this.Controls.Add(this.LogLabel);
            this.Controls.Add(this.OpenOutputDirectoryButton);
            this.Controls.Add(this.BrowseOutputDirectoryButton);
            this.Controls.Add(this.OutputDirectoryTextBox);
            this.Controls.Add(this.OutputDirectoryLabel);
            this.Controls.Add(this.RootNamespaceLabel);
            this.Controls.Add(this.RootNamespaceTextBox);
            this.Controls.Add(this.CompanyNameLabel);
            this.Controls.Add(this.CompanyNameTextBox);
            this.Controls.Add(this.ModelProjectNamespaceLabel);
            this.Controls.Add(this.ModelProjectNamespaceTextBox);
            this.Controls.Add(this.UpdateProjectFilesCheckBox);
            this.Controls.Add(this.VisualBasicRadioButton);
            this.Controls.Add(this.CSharpRadioButton);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(1297, 750);
            this.MinimumSize = new System.Drawing.Size(1297, 750);
            this.Name = "MainForm";
            this.Text = "Solution Maker";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.OpenFileDialog OpenFileDialog;
        internal System.Windows.Forms.CheckBox UpdateProjectFilesCheckBox;
        internal System.Windows.Forms.RadioButton VisualBasicRadioButton;
        internal System.Windows.Forms.RadioButton CSharpRadioButton;
        internal System.Windows.Forms.Label RootNamespaceLabel;
        internal System.Windows.Forms.TextBox RootNamespaceTextBox;
        internal System.Windows.Forms.Label CompanyNameLabel;
        internal System.Windows.Forms.TextBox CompanyNameTextBox;
        internal System.Windows.Forms.Label ModelProjectNamespaceLabel;
        internal System.Windows.Forms.TextBox ModelProjectNamespaceTextBox;
        internal System.Windows.Forms.Label OutputDirectoryLabel;
        internal System.Windows.Forms.TextBox OutputDirectoryTextBox;
        internal System.Windows.Forms.Button OpenOutputDirectoryButton;
        internal System.Windows.Forms.Button BrowseOutputDirectoryButton;
        internal System.Windows.Forms.Label LogLabel;
        internal System.Windows.Forms.TextBox LogTextBox;
        internal System.Windows.Forms.Button GoButton;
        internal System.Windows.Forms.LinkLabel SelectDeselectAllPOCOTypesLinkLabel;
        private System.Windows.Forms.CheckedListBox POCOTypesCheckedListBox;
        internal System.Windows.Forms.Label POCOTypesLabel;
        internal System.Windows.Forms.Label AssemblyLocationLabel;
        internal System.Windows.Forms.TextBox AssemblyLocationTextBox;
        internal System.Windows.Forms.Button BrowseAssemblyLocationButton;
        internal System.Windows.Forms.Button OpenAssemblyLocationButton;
        private System.Windows.Forms.LinkLabel RefreshPOCOListLinkLabel;
        internal System.Windows.Forms.LinkLabel SelectDeselectAllDBObjectsLinkLabel;
        private System.Windows.Forms.CheckBox StoredProceduresCheckBox;
        private System.Windows.Forms.CheckBox ViewsCheckBox;
        private System.Windows.Forms.CheckBox TablesCheckBox;
        private System.Windows.Forms.CheckedListBox DBObjectsCheckedListBox;
        private System.Windows.Forms.LinkLabel RefreshDBListLinkLabel;
        private System.Windows.Forms.Label DatabaseObjectsLabel;
        private System.Windows.Forms.TextBox ConnectionStringTextBox;
        private System.Windows.Forms.Label ConnectionStringLabel;
        internal System.Windows.Forms.FolderBrowserDialog OutputFolderBrowserDialog;
        internal System.Windows.Forms.Label RepositoryProjectNamespaceLabel;
        internal System.Windows.Forms.TextBox RepositoryProjectNamespaceTextBox;
        internal System.Windows.Forms.Label ServiceProjectNamespaceLabel;
        internal System.Windows.Forms.TextBox ServiceProjectNamespaceTextBox;
        internal System.Windows.Forms.LinkLabel DeleteContentsLinkLabel;
        internal System.Windows.Forms.LinkLabel ClearLogLinkLabel;
        private System.Windows.Forms.CheckBox TableValuedFunctionsCheckBox;
        internal System.Windows.Forms.LinkLabel ClearDBObjectsLinkLabel;
        internal System.Windows.Forms.LinkLabel ClearPOCOTypesLinkLabel;
        private System.Windows.Forms.ProgressBar ProgressBar;
        private System.Windows.Forms.Label ProgressLabel;
        internal System.Windows.Forms.LinkLabel ResetLinkLabel;
        internal System.Windows.Forms.TextBox BuiltInTypeTextBox;
        internal System.Windows.Forms.Button AddBuiltInTypeButton;
        private System.Windows.Forms.Label AddBuiltInTypeLabel;
        internal System.Windows.Forms.LinkLabel CopyToClipboardLinkLabel;
        internal System.Windows.Forms.LinkLabel SaveLogAsLinkLabel;
        private System.Windows.Forms.SaveFileDialog SaveFileDialog;
        internal System.Windows.Forms.Button OpenIocMappingsConfigFileButton;
        internal System.Windows.Forms.Button BrowseIocMappingsConfigFileButton;
        internal System.Windows.Forms.TextBox IocMappingsConfigFilePathTextBox;
        internal System.Windows.Forms.Label IocMappingsConfigFileLabel;
    }
}
